export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const MY_ORDER_REQUEST = "MY_ORDER_REQUEST";
export const MY_ORDER_SUCCESS = "MY_ORDER_SUCCESS";
export const MY_ORDER_FAIL = "MY_ORDER_FAIL";

export const ALL_ORDERS_REQUEST = "MY_ORDER_REQUEST";
export const ALL_ORDERS_SUCCESS = "MY_ORDER_SUCCESS";
export const ALL_ORDERS_FAIL = "MY_ORDER_FAIL";

export const UPDATE_ORDER_REQUEST = "MY_ORDER_REQUEST";
export const UPDATE_ORDER_SUCCESS = "MY_ORDER_SUCCESS";
export const UPDATE_ORDER_FAIL = "MY_ORDER_FAIL";
export const UPDATE_ORDER_RESET = "MY_ORDER_FAIL";

export const DELETE_ORDER_REQUEST = "MY_ORDER_REQUEST";
export const DELETE_ORDER_SUCCESS = "MY_ORDER_SUCCESS";
export const DELETE_ORDER_FAIL = "MY_ORDER_FAIL";
export const DELETE_ORDER_RESET = "MY_ORDER_FAIL";

export const ORDER_DETAIL_REQUEST = "MY_ORDER_REQUEST";
export const ORDER_DETAIL_SUCCESS = "MY_ORDER_SUCCESS";
export const ORDER_DETAIL_FAIL = "MY_ORDER_FAIL";
